#before_install:
#- sudo apt-get update -qq
#- sudo apt-get install -qq [packages list]
install: cmake
language: cpp
compiler: clang
python:
  - "3.5"
script: mkdir bin && cd bin && cmake ../ && make && make test