language: cpp

compiler:
  - clang

python: 3.5

sudo: required

os: linux

dist: yakkety

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost-dev

before_script:
  - mkdir bin
  - cd bin
  - cmake ..

script: make
